main: net.urbanmc.treasurehunter.TreasureHunter
name: TreasureHunter
version: 0.1
description: Spawns chests around the world at intervals containing various loot
authors: [Elian, Silverwolfg11]
softdepend: [Multiverse-Core, RandomTP]

commands:
  treasurehunter:
    description: TreasureHunter command
    aliases: [th]

permissions:
  treasurehunter.command:
    default: true